add: PHP 추가
myyrakle/billion_row_challenge pull request #19
Opened 2024-04-14 08:51 UTC by kitrio

PHP 8.3 에서 테스트했습니다

2024-04-14 12:14 UTC, myyrakle reviewed
딱히 최적화 안하고 기본예제로서만 만드신거죠?

2024-04-14 12:30 UTC, myyrakle commented
```
[PHP] rio example
Performance issue please set php.ini opcache.enable_cli=1
PHP Warning:  fopen(/home/myyrakle/Codes/billion_row_challenge/php/measurements.txt): Failed to open stream: No such file or directory in /home/myyrakle/Codes/billion_row_challenge/php/rio.php on line 7
PHP Fatal error:  Uncaught TypeError: stream_get_line(): Argument #1 ($stream) must be of type resource, bool given in /home/myyrakle/Codes/billion_row_challenge/php/rio.php:10
Stack trace:
#0 /home/myyrakle/Codes/billion_row_challenge/php/rio.php(10): stream_get_line()
#1 /home/myyrakle/Codes/billion_row_challenge/php/rio.php(52): challenge()
#2 {main}
  thrown in /home/myyrakle/Codes/billion_row_challenge/php/rio.php on line 10
```

2024-04-14 12:44 UTC, kitrio commented
수정했습니다

2024-04-14 12:58 UTC, myyrakle commented
```
myyrakle@myyrakle:~/Codes/billion_row_challenge$ sh run_php.sh 
[PHP] rio example
Performance issue please set php.ini opcache.enable_cli=1
PHP Warning:  fopen(/home/myyrakle/Codes/billion_row_challenge/php/measurements.txt): Failed to open stream: No such file or directory in /home/myyrakle/Codes/billion_row_challenge/php/rio.php on line 7
PHP Fatal error:  Uncaught TypeError: stream_get_line(): Argument #1 ($stream) must be of type resource, bool given in /home/myyrakle/Codes/billion_row_challenge/php/rio.php:10
Stack trace:
#0 /home/myyrakle/Codes/billion_row_challenge/php/rio.php(10): stream_get_line()
#1 /home/myyrakle/Codes/billion_row_challenge/php/rio.php(52): challenge()
#2 {main}
  thrown in /home/myyrakle/Codes/billion_row_challenge/php/rio.php on line 10
```

이거 왠진 모르겠는데 제멋대로 코드 내 상대경로로 파일을 찾네요

2024-04-14 13:47 UTC, myyrakle requested changes

2024-04-14 13:47 UTC, myyrakle commented on php/rio.php
> +echo $end - $start;
이거 밀리초단위로 출력단위는 통일해주셔야할 것 같아요
"Elapsed {?}ms" 같은 형태로 출력해주시면 좋을 것 같네요.

2024-04-14 13:47 UTC, myyrakle commented on php/rio.php
> +$output = challenge();
output을 ouputs.txt와 비교해서 검증하는 부분은 있어야할 것 같군요.
성공하면 "Test Passed"
실패하면 "Test Failed" 같은 형태로 출력하고 expect와 got 값을 추가로 출력해주는 형태면 좋겠어요

2024-04-15 11:32 UTC, kitrio commented on php/rio.php
> +$output = challenge();
Test passed 수정완료

2024-04-15 16:26 UTC, myyrakle approved these changes
LGTM

2024-04-15 16:26 UTC, merged