Nodejs multi thread 추가
myyrakle/billion_row_challenge pull request #31
Opened 2024-04-15 09:32 UTC by sunrabbit123

2024-04-15 16:13 UTC, myyrakle requested changes
```
<--- Last few GCs --->


<--- JS stacktrace --->


#
# Fatal process OOM in Re-embedded builtins: set permissions
#

Trace/breakpoint trap (core dumped)
```

2024-04-15 17:43 UTC, sunrabbit123 commented
코어 여섯개 선넘네요

2024-04-16 14:02 UTC, myyrakle requested changes
```
myyrakle@myyrakle:~/Codes/billion_row_challenge$ sh nodejs/run_sunrabbit2.sh


#
# Fatal error in , line 0
# Fatal JavaScript invalid size error 169220804
#
#
#
#FailureMessage Object: 0x7fffe6c9cc80
 1: 0xc01371  [node]
 2: 0x1e806a4 V8_Fatal(char const*, ...) [node]
 3: 0xf13dce  [node]
 4: 0x10c4fb8  [node]
 5: 0x10c5355  [node]
 6: 0x12d14db v8::internal::Runtime_GrowArrayElements(int, unsigned long*, v8::internal::Isolate*) [node]
 7: 0x170deb9  [node]
Trace/breakpoint trap (core dumped)
```

2024-04-16 14:04 UTC, sunrabbit123 commented
인생이 쓰네요

2024-04-16 14:05 UTC, sunrabbit123 commented
32bit라 그런가

2024-04-16 14:24 UTC, myyrakle commented
```
myyrakle@myyrakle:~/Codes/billion_row_challenge$ sh nodejs/run_sunrabbit2.sh
node:internal/fs/promises:692
    validatePosition(position, 'position', length);
    ^

RangeError [ERR_OUT_OF_RANGE]: The value of "position" is out of range. It must be >= -1 && <= 9007199254740991. Received -639420349
    at read (node:internal/fs/promises:692:5)
    at fsCall (node:internal/fs/promises:463:18)
    at FileHandle.read (node:internal/fs/promises:194:12)
    at solution (/home/myyrakle/Codes/billion_row_challenge/nodejs/sunrabbit2/index.js:141:16)
    at async main (/home/myyrakle/Codes/billion_row_challenge/nodejs/sunrabbit2/index.js:211:15) {
  code: 'ERR_OUT_OF_RANGE'
}

Node.js v21.7.3
```

2024-04-18 02:17 UTC, sunrabbit123 commented
테스트 통과하는데요

2024-04-18 02:18 UTC, sunrabbit123 commented
환경 정확히주세요

2024-04-18 14:58 UTC, myyrakle commented
처음에는 v18이었는데 v20로 테스트하셔서 안맞았던거같은데요

2024-04-18 14:59 UTC, myyrakle approved these changes
LGBTM

2024-04-18 15:00 UTC, merged

2024-04-19 02:27 UTC, sunrabbit123 commented
근데 이 짓해도 느리네요 에잉